### ISSUE TITLE
l2 norm + Normalization

### ISSUE THREAD

**Issue by sungyoon-lee** [KaidiXu/auto_LiRPA#3]
Hi, thank you for the nice implementations!

I have a question on running l2 norm application with data normalization.
While data is normalized, it seems like the perturbation \epsilon is not scaled wrt data.std.
Correct me if i'm wrong.

Thank you in advance
~ Lee

**Comment by huanzhang12** [comment]
@sungyoon-lee Can you provide more details? Which python script you are using for L2 norm robust training? Thanks.

**Comment by sungyoon-lee** [comment]
@huanzhang12 
I meant  https://github.com/KaidiXu/auto_LiRPA/blob/master/examples/vision/simple_training.py
I've run another code for IBP under l2 norm 36/255 in CROWN-IBP (https://github.com/huanzhang12/CROWN-IBP/blob/master/train.py). When data is normalized, as mentioned in https://github.com/huanzhang12/CROWN-IBP/blob/master/train.py#L128, I think I should use different eps (Correct me if i'm wrong). For example, if std=(0.2,0.2,0.2), then I have to use eps=36/255/0.2 instead of eps=36/255. Thus, when I fix the eps=36/255 and use different setting "training_params:loader_params:normalize_input=true/false", they have shown significantly different results. However, most of the loader (e.g. CIFAR-10: std = [0.2023, 0.1994, 0.2010]) uses different std's per channel.
Similarly in https://github.com/KaidiXu/auto_LiRPA/blob/master/examples/vision/simple_training.py#L75, it seems like there is no difference. Do I have to manually change the loader to have same std's per channel in https://github.com/KaidiXu/auto_LiRPA/blob/83206c7c4620174da4bb4e3d5e72ef211076e10c/examples/vision/datasets.py#L58
Maybe I should have make this issue in CROWN-IBP. I hope this can provide enough details. Thank you in advance!

**Comment by huanzhang12** [comment]
I see. Indeed in `simple_training.py` we did not add normalization for other norms. I only tested to train L2 perturbation on MNIST/Fashion MNIST so this has not been handled for CIFAR.

When the input is normalized, the network receives a scaled input but we still need to guarantee the L2 perturbation is less than epsilon on the original, unnormalized input. Essentially, this makes the perturbation epsilon ball becomes an ellipsoid instead of a ball for the normalized input. You will need to slightly modify here: https://github.com/KaidiXu/auto_LiRPA/blob/master/auto_LiRPA/perturbations.py#L114 to use a vector of eps as input considering the perturbation is an ellipsoid rather than a ball.

A simpler solution would be using a normalizing factor like 0.2, 0.2, 0.2 so the scaled epsilon ball is still a ball, and you can directly use eps/0.2 as the effective eps for training.

**Comment by sungyoon-lee** [comment]
Thank you!
